line chart shadow option
indiespirit/react-native-chart-kit pull request #561
Opened 2021-10-01 22:23 UTC by Kaienss

Added one option to dataset
shadowColor: similar to color, if not provided, shadow color for the dataset will be the same as the line color with useShadowColorFromDataset:true,
if useShadowColorFromDataset:false,
shadow color will be chartConfig.color.

shadow color is applied with following priority.
dataset.shadowColor -> dataset.color -> chartConfig.color

2022-02-08 03:58 UTC, Hermanya commented on src/line-chart/LineChart.tsx
> +    return (dataset.shadowColor || dataset.color || this.props.chartConfig.color)(opacity);
I feel like it should default to `url(#fillShadowGradient`..., to make this change backwards compatible

2022-02-08 03:59 UTC, Hermanya requested changes
this change looks like it would change behaviour for existing users

2023-02-18 10:35 UTC, codeplaygoa commented
@Kaienss @Hermanya any update here. I badly need this feature

2023-04-17 21:32 UTC, josh-thompson13 approved these changes
Approved.

2026-06-27 18:42 UTC, bermanto commented
v7.0.0 is now available, so we're closing older issues and PRs from previous versions to keep the tracker focused on the current release. Please try the new version, and if you still have an issue, open a new one with the latest details and a reproduction.

2026-06-27 18:42 UTC, closed without merging